---
- hosts: aws_ec2
  become: yes
  gather_facts: no
  remote_user: ubuntu

  vars_files:
    - vars/main.yml

  roles:
    - role: geerlingguy.github-users
      tags: ['accounts', 'ssh', 'github']
